WITH ODR AS (SELECT O_ORDERKEY, O_CUSTKEY, O_ORDERSTATUS, O_TOTALPRICE, O_ORDERDATE FROM {{ source('stg_view', 'ORDERS') }}),
LINEITEM AS (SELECT L_ORDERKEY, L_LINENUMBER, L_LINESTATUS,L_QUANTITY, L_EXTENDEDPRICE, L_DISCOUNT, L_TAX FROM {{ source('stg_view', 'LINEITEM') }})
SELECT 
O_ORDERKEY AS ORDERKEY,  
O_ORDERSTATUS AS ORDERSTATUS,
O_ORDERDATE AS ORDERDATE,
L_LINENUMBER AS LINENUMBER,
L_LINESTATUS AS LINESTATUS,
O_TOTALPRICE AS TOTALPRICE,
L_EXTENDEDPRICE AS LINEEXTENDEDPRICE, 
L_DISCOUNT AS LINEDISCOUNT,
L_TAX AS LINETAX,
L_QUANTITY AS QUANTITY,
O_CUSTKEY AS CUST_KEY,
ORDERKEY ||'~'|| LINENUMBER AS INTEGRATION_ID
FROM ODR LEFT JOIN LINEITEM ON ODR.O_ORDERKEY = LINEITEM.L_ORDERKEY